version: '3'
services:
  ngproxy:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - proxy-bridge

  dropwiz:
    build: .
    image: dropwiz
    container_name: dropwiz
    restart: always
    expose:
      - "8080"
      - "8081"
    networks:
      - proxy-bridge

# For some reason the metrics are not being sent to Graphite. So disabling it for now.
        #graphite:
        #    image: rvernica/graphite
        #    container_name: graphite
        #    restart: always
        #    expose:
        #      - "2003"
        #    volumes:
        #      - /opt/dropwiz-graphite/metrics:/opt/graphite/storage/whisper
        #    networks:
        #    - proxy-bridge

networks:
  proxy-bridge:
